# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc/basic.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='grpc/basic.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10grpc/basic.proto\"\xc1\x01\n\tTrainInfo\x12\x0c\n\x04guid\x18\x01 \x01(\t\x12\x12\n\nnum_epochs\x18\x02 \x01(\x05\x12\x10\n\x08num_gpus\x18\x03 \x03(\x05\x12\x12\n\nhidden_dim\x18\x04 \x01(\x05\x12\x16\n\x0eword_tag_split\x18\x05 \x01(\t\x12\x0f\n\x07pattern\x18\x06 \x01(\t\x12\x16\n\x0epadding_length\x18\x07 \x01(\x05\x12\x12\n\nbatch_size\x18\x08 \x01(\x05\x12\x17\n\x0f\x65val_batch_size\x18\t \x01(\x05\"@\n\x0bPredictInfo\x12\x0c\n\x04guid\x18\x01 \x01(\t\x12\x0f\n\x07use_gpu\x18\x02 \x01(\x08\x12\x12\n\nhidden_dim\x18\x03 \x01(\x05\")\n\x07GetInfo\x12\x0c\n\x04guid\x18\x01 \x01(\t\x12\x10\n\x08model_id\x18\x02 \x01(\t\"*\n\x08Response\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\t\"&\n\x08\x46ileBody\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x66ile\x18\x02 \x01(\x0c\x32w\n\x04Task\x12%\n\x0b\x63reateTrain\x12\t.FileBody\x1a\t.Response(\x01\x12\x1f\n\x08getModel\x12\x08.GetInfo\x1a\t.Response\x12\'\n\rcreatePredict\x12\t.FileBody\x1a\t.Response(\x01\x32)\n\x05Train\x12 \n\x05train\x12\n.TrainInfo\x1a\t.Response0\x01\x32*\n\x07Predict\x12\x1f\n\x04pred\x12\x0c.PredictInfo\x1a\t.Responseb\x06proto3'
)




_TRAININFO = _descriptor.Descriptor(
  name='TrainInfo',
  full_name='TrainInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='guid', full_name='TrainInfo.guid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_epochs', full_name='TrainInfo.num_epochs', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_gpus', full_name='TrainInfo.num_gpus', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hidden_dim', full_name='TrainInfo.hidden_dim', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='word_tag_split', full_name='TrainInfo.word_tag_split', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pattern', full_name='TrainInfo.pattern', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='padding_length', full_name='TrainInfo.padding_length', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='batch_size', full_name='TrainInfo.batch_size', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='eval_batch_size', full_name='TrainInfo.eval_batch_size', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=214,
)


_PREDICTINFO = _descriptor.Descriptor(
  name='PredictInfo',
  full_name='PredictInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='guid', full_name='PredictInfo.guid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='use_gpu', full_name='PredictInfo.use_gpu', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hidden_dim', full_name='PredictInfo.hidden_dim', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=280,
)


_GETINFO = _descriptor.Descriptor(
  name='GetInfo',
  full_name='GetInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='guid', full_name='GetInfo.guid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model_id', full_name='GetInfo.model_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=282,
  serialized_end=323,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='Response.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='result', full_name='Response.result', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=325,
  serialized_end=367,
)


_FILEBODY = _descriptor.Descriptor(
  name='FileBody',
  full_name='FileBody',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='FileBody.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='file', full_name='FileBody.file', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=369,
  serialized_end=407,
)

DESCRIPTOR.message_types_by_name['TrainInfo'] = _TRAININFO
DESCRIPTOR.message_types_by_name['PredictInfo'] = _PREDICTINFO
DESCRIPTOR.message_types_by_name['GetInfo'] = _GETINFO
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['FileBody'] = _FILEBODY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TrainInfo = _reflection.GeneratedProtocolMessageType('TrainInfo', (_message.Message,), {
  'DESCRIPTOR' : _TRAININFO,
  '__module__' : 'grpc.basic_pb2'
  # @@protoc_insertion_point(class_scope:TrainInfo)
  })
_sym_db.RegisterMessage(TrainInfo)

PredictInfo = _reflection.GeneratedProtocolMessageType('PredictInfo', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTINFO,
  '__module__' : 'grpc.basic_pb2'
  # @@protoc_insertion_point(class_scope:PredictInfo)
  })
_sym_db.RegisterMessage(PredictInfo)

GetInfo = _reflection.GeneratedProtocolMessageType('GetInfo', (_message.Message,), {
  'DESCRIPTOR' : _GETINFO,
  '__module__' : 'grpc.basic_pb2'
  # @@protoc_insertion_point(class_scope:GetInfo)
  })
_sym_db.RegisterMessage(GetInfo)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'grpc.basic_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  })
_sym_db.RegisterMessage(Response)

FileBody = _reflection.GeneratedProtocolMessageType('FileBody', (_message.Message,), {
  'DESCRIPTOR' : _FILEBODY,
  '__module__' : 'grpc.basic_pb2'
  # @@protoc_insertion_point(class_scope:FileBody)
  })
_sym_db.RegisterMessage(FileBody)



_TASK = _descriptor.ServiceDescriptor(
  name='Task',
  full_name='Task',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=409,
  serialized_end=528,
  methods=[
  _descriptor.MethodDescriptor(
    name='createTrain',
    full_name='Task.createTrain',
    index=0,
    containing_service=None,
    input_type=_FILEBODY,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getModel',
    full_name='Task.getModel',
    index=1,
    containing_service=None,
    input_type=_GETINFO,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='createPredict',
    full_name='Task.createPredict',
    index=2,
    containing_service=None,
    input_type=_FILEBODY,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TASK)

DESCRIPTOR.services_by_name['Task'] = _TASK


_TRAIN = _descriptor.ServiceDescriptor(
  name='Train',
  full_name='Train',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=530,
  serialized_end=571,
  methods=[
  _descriptor.MethodDescriptor(
    name='train',
    full_name='Train.train',
    index=0,
    containing_service=None,
    input_type=_TRAININFO,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRAIN)

DESCRIPTOR.services_by_name['Train'] = _TRAIN


_PREDICT = _descriptor.ServiceDescriptor(
  name='Predict',
  full_name='Predict',
  file=DESCRIPTOR,
  index=2,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=573,
  serialized_end=615,
  methods=[
  _descriptor.MethodDescriptor(
    name='pred',
    full_name='Predict.pred',
    index=0,
    containing_service=None,
    input_type=_PREDICTINFO,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PREDICT)

DESCRIPTOR.services_by_name['Predict'] = _PREDICT

# @@protoc_insertion_point(module_scope)
